Emulate initialization and phase alpha, up to the start of phase beta
MusIF-MIAI/gemu pull request #5
Opened 2022-09-12 16:08 UTC by biappi

I've fleshed out more the implementation of the MSL a bit.

With this pr the emulation goes thru the initialisation phase and the alpha phase. I've hardcoded some of the conditions to check if the logic was sound, and i've only implemented commands that change the state register `SO`.

Also, i've added some printfs to check what the emulation is doing, this is the log of a run so far.

```
State 80 - Initialitiation

Running state 80
implement command CI19
implement command CO96
implement command CO97
implement command CO00
implement command CO02
implement command CI32
implement command CI05
implement command CI08
implement command CI76
implement command CI80
implement command CI81
implement command CI82

State E2+E3 - Alpha Phase

Running state E2
implement command CO10
implement command CO41
implement command CO30
implement command CO02
implement command CI67
implement command CI62
implement command CI08
implement command CI80
implement command CI83
Running state E0
implement command CO12
implement command CO41
implement command CO30
implement command CO00
implement command NONE
implement command CI67
implement command CI62
implement command CI39
implement command CI05

State 64+65 - Beta Phase

Running state 64
no timing charts found for state 64
Program ended with exit code: 1
```

2022-09-13 09:41 UTC, rizlik130 requested changes
can you just remove old implementation?

2022-09-13 09:41 UTC, rizlik130 commented on ge.c
> +        for (int i = 0; i < state->count; i++) {
If we always order the charts inside the state we may avoid resetting i here

2022-09-13 09:41 UTC, rizlik130 commented on ge.c
> +        for (int i = 0; i < state->count; i++) {
we should add do_pulse here

2022-09-13 19:06 UTC, danielinux requested changes
please eliminate the 'NONE' micro-operation

2022-09-13 19:06 UTC, danielinux commented on msl-commands.h
> +void NONE(struct ge*);
please remove commands that are not based on documented operations

2022-09-13 19:06 UTC, danielinux commented on msl-states.h
> +    { TO50, NONE, 0 }, // NO -> BO
This is an intrinsic master pulse event, and will be executed on `on_TO50` through `do_pulse`. Please remove

2022-09-13 19:06 UTC, danielinux commented on msl-states.h
> +    { TO50, NONE, 0 }, // NO -> BO
see above

2022-09-13 19:06 UTC, danielinux commented on msl-states.h
> +    { TO50, NONE, 0 }, // NO -> BO
same

2022-09-13 19:06 UTC, danielinux commented on msl-states.h
> +    { TO50, NONE, 0 }, // NO -> BO
here too

2022-09-13 19:06 UTC, danielinux commented on msl-states.h
> +    { TO50, NONE, 0 }, // NO -> BO
one more

2022-09-14 19:33 UTC, rizlik130 approved these changes

2022-09-14 20:08 UTC, merged